[package]
name = "baloo"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
